### ISSUE TITLE
第三題

### ISSUE THREAD

**Issue by daphnechen00** [NCU-CSIE-Algorithmics-A-1061/Homework-1#10]
第13組

**Comment by daphnechen00** [comment]
How to implement merge-sort such that the extra space used is about n/2 where n is the number of input elements?

**Comment by daphnechen00** [comment]
假設input是n
在merge的階段使用b(extra space)
m=n/2
b=a[1..m]
merge時拿a[1..m] a[m+1..n] (sort好的兩個array)
用recursive call a[1..m] a[m+1..n]來排序
排序後的結果會存放到a
如果不使用extra space b，直接用a[1..m]和a[m+1..n]會覆蓋到a[1..m]
導致排序錯誤
所以把a[1..m]複製到b，用b和a[m+1..n]比較
所以b會使用到的空間是n/2

我們的討論結果

**Comment by daphnechen00** [comment]
我們不確定是不是這樣打
請助教幫我們看看
謝謝

**Comment by daphnechen00** [comment]
[演算法第3題 9-26.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1329463/3.9-26.pptx)

**Comment by daphnechen00** [comment]
![20310](https://user-images.githubusercontent.com/32240324/30809249-b3d11984-a233-11e7-92d9-f644979865f7.jpg)

**Comment by scps940707** [comment]
記得在實習課有給你們建議，可以把那張照片用電腦重繪一次，並把ppt更新成更精美的圖解。

你們有沒有打算上傳精美版本可以留言知會助教一下嗎？沒有這個打算也沒關係，助教會馬上merge這個issue後就不再接受更新；有打算要改版也說一聲，助教也願意用自己的青春年華等待你們的改版。



###### ppt的品質是助教的獨斷評分依據之一！

**Comment by daphnechen00** [comment]
你好

我們會再上船精美版本

謝謝

WF <notifications@github.com> 於 2017年9月27日 下午10:54 寫道：

**Comment by juhuitseng** [comment]
# Problem
How to implement merge-sort such that the extra space used is about n/2 where n is the number of input elements?

# Data structure
Array

# Assume
Array A(declare A[n]) is the original unsorted array which has stored two sorted groups of elements respectively in A[0]~A[n/2] and A[n/2+1]~A[m]

# Solution
Since we have to merge the two sorted groups of elements (A[0]~A[n/2] and A[n/2+1]~A[m] ) into one, we can copy A[0]~A[n/2] to a new array B(declare B[n/2]) and discard data in A[0]~A[n/2].
Then merge the two sorted groups of elements A[n/2+1]~A[m] and B[0]~B[n/2] and put results one by one into A from index 0 to index n

# Conclution
The extra space for this kind of implement of merge sort is array B, whose length is only the half of the original array A.
A’s length is the number of input elements n
The extra space used is about n/2

**Comment by juhuitseng** [comment]
[第3題_13組modify.pptx](https://github.com/NCU-CSIE-Algorithmics-A-1061/Homework-1/files/1339308/3._13.modify.pptx)

p.s.精美圖在ppt中~

**Comment by scps940707** [comment]
已經收到了！

**Comment by scps940707** [comment]
@daphnechen00 @juhuitseng

請到 #14 確認一下

**Comment by c910335** [comment]
@juhuitseng

> Data structure
> Array

這段太廢話

> Assume
> Array A(declare A[n]) is the original unsorted array which has stored two sorted groups of elements respectively in A[0]~A[n/2] and A[n/2+1]~A[m]

題目是 merge sort，不是 merge 兩個排好的陣列。
你做得到這個題目不代表原題也做得到，
你必須加上為何原題也做得到的解釋。

**Comment by juhuitseng** [comment]
# Problem
How to implement merge-sort such that the extra space used is about n/2 where n is the number of input elements?

# Assume
We use button-up approach:
```
loop( A's length from i=2 to the number of input elements n)
{
  Array A(declare A[i]) is the original unsorted array which has stored two sorted groups of elements 
  respectively in A[0]~A[i/2] and A[i/2+1]~A[i].
  i=i*2.
}
```
For example, 
if length i=2, A have two sorted array, which is A[0] and A[1], respectively.
If length i=4, A have two sorted array(sorted from previous step), which is A[0]~A[1] and A[2]~A[3], respectively.
......
If length i=n, A have two sorted array(sorted from previous step), which is A[0]~A[n/2] and A[n/2+1]~A[n], respectively.
The merge sort is done.

# Solution
Since we have to merge the two sorted groups of elements (A[0]~A[n/2] and A[n/2+1]~A[n] ) into one, we can copy A[0]~A[n/2] to a new array B(declare B[n/2]) and discard data in A[0]~A[n/2].
Then merge the two sorted groups of elements A[n/2+1]~A[m] and B[0]~B[n/2] and put results one by one into A from index 0 to index n

# Conclution
The extra space for this kind of implement of merge sort is array B, whose length is only the half of the original array A.
A’s length is the number of input elements n
The extra space used is about n/2

**Comment by c910335** [comment]
每次合併兩個陣列的時候都用了 n/2 的額外空間
但是 Merge Sort 並不是只合併一次
把每次合併的額外空間都加起來的話
會得到 ![n/2*logn](http://latex.codecogs.com/gif.latex?%5Cfrac%7Bn%7D%7B2%7Dlogn)
顯然不符題目要求

**Comment by juhuitseng** [comment]
每次只會發生一個合併，所以當這次合併好後就可以釋放記憶體供下個合併時所需的額外記憶體用。
而當在合併A[0]~A[n/2]和A[n/2+1]~A[n] (n是input大小)時所需的額外空間最大(n/2)，所以額外花的空間是n/2。

**Comment by c910335** [comment]
所以這件事得寫進解答裡面

**Comment by juhuitseng** [comment]
# Problem
How to implement merge-sort such that the extra space used is about n/2 where n is the number of input elements?

# Assume
We use button-up approach:
```
loop( A's length from i=2 to the number of input elements n)
{
  Array A(declare A[i]) is the original unsorted array which has stored two sorted groups of elements 
  respectively in A[0]~A[i/2] and A[i/2+1]~A[i].
  i=i*2.
}
```
For example, 
if length i=2, A have two sorted array, which is A[0] and A[1], respectively.
If length i=4, A have two sorted array(sorted from previous step), which is A[0]~A[1] and A[2]~A[3], respectively.
......
If length i=n, A have two sorted array(sorted from previous step), which is A[0]~A[n/2] and A[n/2+1]~A[n], respectively.
The merge sort is done.

# Solution
Since we have to merge the two sorted groups of elements (A[0]~A[n/2] and A[n/2+1]~A[n] ) into one, we can copy A[0]~A[n/2] to a new array B(declare B[n/2]) and discard data in A[0]~A[n/2].
Then merge the two sorted groups of elements A[n/2+1]~A[m] and B[0]~B[n/2] and put results one by one into A from index 0 to index n

# Conclution
The extra space for this kind of implement of merge sort is array B, whose length is only the half of the original array A.
A’s length is the number of input elements n
The extra space used is about n/2

*Note: 每次只會發生一個合併，所以當這次合併好後就可以釋放記憶體供下個合併時所需的額外記憶體用。
而當在合併A[0]~A[n/2]和A[n/2+1]~A[n] (n是input大小)時所需的額外空間最大(n/2)，所以額外花的空間是n/2。
